doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '12.4'
        driver: pdo_pgsql
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            userId: Cfi\Infrastructure\Doctrine\DBAL\Type\UserIdType
            wordId: Cfi\Infrastructure\Doctrine\DBAL\Type\WordIdType
            ipAddress: Cfi\Infrastructure\Doctrine\DBAL\Type\IpAddressType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Models:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping'
                prefix: 'Cfi\Domain\Model'
                alias: Models
