jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        infer_types_from_doctrine_metadata: false
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
    property_naming: JMS\Serializer\Naming\PropertyNamingStrategyInterface
    default_context:
        serialization:
            serialize_null: true
        deserialization:
            serialize_null: true
