add_text:
  path: /users/{userId}/text
  methods: [POST]
  controller: Cfi\Application\Controller\AddTextController

list_user_text:
  path: /users/{userId}/text
  methods: [GET]
  controller: Cfi\Application\Controller\ListUserTextController

create_user:
  path: /users
  methods: [POST]
  controller: Cfi\Application\Controller\CreateUserController
